using arc.app.Common;

namespace arc.app.Config.Mapper
{
    internal class WHONETExportMapper : IDefinition
    {
        public string Get()
        {
            return @"{  
                        'Name': 'whonetexportmapper', 
                        'Type': 'Standard',
                        'IncludeIfNotFound': true,
                        'PassthroughIfNoRule': true,
                        'Rules': [
                            { Key: '<:3:>', Type: 'Mapping', Source: 'Age', Value: 'Age' },
                            { Key: '<:4:>', Type: 'Mapping', Source: 'Province', Value: 'Province' },
                            { Key: '<:5:>', Type: 'Mapping', Source: 'District', Value: 'District' },
                            { Key: '<:6:>', Type: 'Mapping', Source: 'SubDistrict', Value: 'SubDistrict' },
                            { Key: '<:7:>', Type: 'Mapping', Source: 'DateOfBirth', Value: 'DateOfBirth' },
                            { Key: '<:8:>', Type: 'Mapping', Source: 'TelephoneNumber', Value: 'TelephoneNumber' },
                            { Key: '<:9:>', Type: 'Mapping', Source: 'Gender', Value: 'Gender' },
                            { Key: '<:10:>', Type: 'Mapping', Source: 'PatientRef', Value: 'PatientRef' },
                            { Key: '<:11:>', Type: 'Mapping', Source: 'AccessionNumber', Value: 'AccessionNumber' },
                            { Key: '<:12:>', Type: 'Mapping', Source: 'Surname', Value: 'Surname' },
                            { Key: '<:13:>', Type: 'Mapping', Source: 'PatientLocation', Value: 'PatientLocation' },
                            { Key: '<:14:>', Type: 'Mapping', Source: 'Organisation', Value: 'Organisation' },
                            { Key: '<:15:>', Type: 'Mapping', Source: 'AdmissionDate', Value: 'AdmissionDate' },
                            { Key: '<:16:>', Type: 'Mapping', Source: 'ClinicalContactNo', Value: 'ClinicalContactNo' },
                            { Key: '<:17:>', Type: 'Mapping', Source: 'Diagnosis', Value: 'Diagnosis' },
                            { Key: '<:18:>', Type: 'Mapping', Source: 'CollectionDate', Value: 'CollectionDate' },
                            { Key: '<:19:>', Type: 'Mapping', Source: 'SpecimenType', Value: 'SpecimenType' },
                            { Key: '<:20:>', Type: 'Mapping', Source: 'SpecimenSite', Value: 'SpecimenSite' },
                            { Key: '<:21:>', Type: 'Mapping', Source: 'Existingbarcode', Value: 'Existingbarcode' },
                            { Key: '<:22:>', Type: 'Mapping', Source: 'ReceivedDate', Value: 'ReceivedDate' },
                            { Key: '<:23:>', Type: 'Mapping', Source: 'ReceivedCondition', Value: 'ReceivedCondition' },
                            { Key: '<:24:>', Type: 'Mapping', Source: 'CollectionTime', Value: 'CollectionTime' },
                            { Key: '<:25:>', Type: 'Mapping', Source: 'ReceivedTime', Value: 'ReceivedTime' },
                            { Key: '<:26:>', Type: 'Mapping', Source: 'State', Value: 'State' },
                            { Key: '<:27:>', Type: 'Mapping', Source: 'SpecimenAppearance', Value: 'SpecimenAppearance' },
                            { Key: '<:28:>', Type: 'Mapping', Source: 'SpecimenOrganism', Value: 'SpecimenOrganism' },
                            { Key: '<:29:>', Type: 'Mapping', Source: 'SpecimenQuantity', Value: 'SpecimenQuantity' },
                            { Key: '<:30:>', Type: 'Mapping', Source: 'SpecimenApiIdPanel', Value: 'SpecimenApiIdPanel' },
                            { Key: '<:31:>', Type: 'Mapping', Source: 'IdProfile', Value: 'IdProfile' },
                            { Key: '<:32:>', Type: 'Mapping', Source: 'IdPercentage', Value: 'IdPercentage' },
                            { Key: '<:33:>', Type: 'Mapping', Source: 'PositiveDate', Value: 'PositiveDate' },
                            { Key: '<:34:>', Type: 'Mapping', Source: 'PositiveTime', Value: 'PositiveTime' },
                            { Key: '<:35:>', Type: 'Mapping', Source: 'SeroType', Value: 'SeroType' },
                            { Key: '<:36:>', Type: 'Mapping', Source: 'SeroTypeProfile', Value: 'SeroTypeProfile' },
                            { Key: '<:37:>', Type: 'Mapping', Source: 'CommentOne', Value: 'CommentOne' },
                            { Key: '<:38:>', Type: 'Mapping', Source: 'CommentTwo', Value: 'CommentTwo' },
                            { Key: '<:39:>', Type: 'Mapping', Source: 'AdditionalNotes', Value: 'AdditionalNotes' },
                            { Key: '<:40:>', Type: 'Mapping', Source: 'AloquatId', Value: 'AloquatId' },
                            { Key: '<:41:>', Type: 'Mapping', Source: 'DisplayOnReport', Value: 'DisplayOnReport' },
                            { Key: '<:42:>', Type: 'Mapping', Source: 'ESBL', Value: 'ESBL' },
                            { Key: '<:43:>', Type: 'Mapping', Source: 'betalactamase', Value: 'betalactamase' },
                            { Key: '<:44:>', Type: 'Mapping', Source: 'location', Value: 'location' }
                        ],
                        'Target':
                            {
                                'PATIENT_ID':'<:10:>',
                                'SEX':'<:9:>',
                                'AGE':'<:3:>',
                                'DATE_BIRTH':'<:7:>',
                                'LOCATION':'<:44:>',
                                'CLIENT':'<:14:>',
                                'SPEC_NUM':'<:11:>',
                                'SPEC_DATE':'<:18:>',
                                'SPEC_TYPE':'<:19:>',
                                'DATE_DATA':'<:33:>',
                                'ORGANISM':'<:28:>',
                                'COMMENT':'<:39:>',
                                'ESBL':'<:42:>',
                                'Betalactamase':'<:43:>'
                            }
                     }";
        }
    }
}


//{ Key: '<:1:>', Type: 'Mapping', Source: 'FirstName', Value: 'FirstName' },
//{ Key: '<:2:>', Type: 'Mapping', Source: 'Surname', Value: 'Surname' },

//'FIRST_NAME':'<:1:>',
//'LAST_NAME':'<:2:>',


//{ Key: '<:46:>', Type: 'Mapping', Source: 'AMC_ND20', Value: 'AMC_ND20' },
//{ Key: '<:47:>', Type: 'Mapping', Source: 'AMP_ND10', Value: 'AMP_ND10' },
//{ Key: '<:48:>', Type: 'Mapping', Source: 'FEP_ND30', Value: 'FEP_ND30' },
//{ Key: '<:49:>', Type: 'Mapping', Source: 'FOX_ND30', Value: 'FOX_ND30' },
//{ Key: '<:50:>', Type: 'Mapping', Source: 'CPD_ND10', Value: 'CPD_ND10' },
//{ Key: '<:51:>', Type: 'Mapping', Source: 'CAZ_ND30', Value: 'CAZ_ND30' },
//{ Key: '<:52:>', Type: 'Mapping', Source: 'CRO_ND30', Value: 'CRO_ND30' },
//{ Key: '<:53:>', Type: 'Mapping', Source: 'CHL_ND30', Value: 'CHL_ND30' },
//{ Key: '<:54:>', Type: 'Mapping', Source: 'CIP_ND5', Value: 'CIP_ND5' },
//{ Key: '<:55:>', Type: 'Mapping', Source: 'CLI_ND2', Value: 'CLI_ND2' },
//{ Key: '<:56:>', Type: 'Mapping', Source: 'DOX_ND30', Value: 'DOX_ND30' },
//{ Key: '<:57:>', Type: 'Mapping', Source: 'ERY_ND15', Value: 'ERY_ND15' },
//{ Key: '<:58:>', Type: 'Mapping', Source: 'GEN_ND10', Value: 'GEN_ND10' },
//{ Key: '<:59:>', Type: 'Mapping', Source: 'MEM_ND10', Value: 'MEM_ND10' },
//{ Key: '<:60:>', Type: 'Mapping', Source: 'NIT_ND300', Value: 'NIT_ND300' },
//{ Key: '<:61:>', Type: 'Mapping', Source: 'OXA_ND1', Value: 'OXA_ND1' },
//{ Key: '<:62:>', Type: 'Mapping', Source: 'PEN_ND10', Value: 'PEN_ND10' },
//{ Key: '<:63:>', Type: 'Mapping', Source: 'RIF_ND5', Value: 'RIF_ND5' },
//{ Key: '<:64:>', Type: 'Mapping', Source: 'TCY_ND30', Value: 'TCY_ND30' },
//{ Key: '<:65:>', Type: 'Mapping', Source: 'SXT_ND1_2', Value: 'SXT_ND1_2' },
//{ Key: '<:66:>', Type: 'Mapping', Source: 'VAN_ND30', Value: 'VAN_ND30' },
//{ Key: '<:67:>', Type: 'Mapping', Source: 'AZM_NE', Value: 'AZM_NE' },
//{ Key: '<:68:>', Type: 'Mapping', Source: 'CRO_NE', Value: 'CRO_NE' },
//{ Key: '<:69:>', Type: 'Mapping', Source: 'CIP_NE', Value: 'CIP_NE' },
//{ Key: '<:70:>', Type: 'Mapping', Source: 'PEN_NE', Value: 'PEN_NE' },
//{ Key: '<:71:>', Type: 'Mapping', Source: 'SXT_NE', Value: 'SXT_NE' },
//{ Key: '<:72:>', Type: 'Mapping', Source: 'VAN_NE', Value: 'VAN_NE' },
//{ Key: '<:73:>', Type: 'Mapping', Source: 'AMC_NM', Value: 'AMC_NM' },
//{ Key: '<:74:>', Type: 'Mapping', Source: 'AMB_NM', Value: 'AMB_NM' },
//{ Key: '<:75:>', Type: 'Mapping', Source: 'AMP_NM', Value: 'AMP_NM' },
//{ Key: '<:76:>', Type: 'Mapping', Source: 'ATM_NM', Value: 'ATM_NM' },
//{ Key: '<:77:>', Type: 'Mapping', Source: 'CAS_NM', Value: 'CAS_NM' },
//{ Key: '<:78:>', Type: 'Mapping', Source: 'CZO_NM', Value: 'CZO_NM' },
//{ Key: '<:79:>', Type: 'Mapping', Source: 'FEP_NM', Value: 'FEP_NM' },
//{ Key: '<:80:>', Type: 'Mapping', Source: 'CTX_NM', Value: 'CTX_NM' },
//{ Key: '<:81:>', Type: 'Mapping', Source: 'CRO_NM', Value: 'CRO_NM' },
//{ Key: '<:82:>', Type: 'Mapping', Source: 'CHL_NM', Value: 'CHL_NM' },
//{ Key: '<:83:>', Type: 'Mapping', Source: 'CIP_NM', Value: 'CIP_NM' },
//{ Key: '<:84:>', Type: 'Mapping', Source: 'CLI_NM', Value: 'CLI_NM' },
//{ Key: '<:85:>', Type: 'Mapping', Source: 'ETP_NM', Value: 'ETP_NM' },
//{ Key: '<:86:>', Type: 'Mapping', Source: 'ERY_NM', Value: 'ERY_NM' },
//{ Key: '<:87:>', Type: 'Mapping', Source: 'FLU_NM', Value: 'FLU_NM' },
//{ Key: '<:88:>', Type: 'Mapping', Source: 'GEN_NM', Value: 'GEN_NM' },
//{ Key: '<:89:>', Type: 'Mapping', Source: 'IPM_NM', Value: 'IPM_NM' },
//{ Key: '<:90:>', Type: 'Mapping', Source: 'LVX_NM', Value: 'LVX_NM' },
//{ Key: '<:91:>', Type: 'Mapping', Source: 'LNZ_NM', Value: 'LNZ_NM' },
//{ Key: '<:92:>', Type: 'Mapping', Source: 'MEM_NM', Value: 'MEM_NM' },
//{ Key: '<:93:>', Type: 'Mapping', Source: 'MIF_NM', Value: 'MIF_NM' },
//{ Key: '<:94:>', Type: 'Mapping', Source: 'MFX_NM', Value: 'MFX_NM' },
//{ Key: '<:95:>', Type: 'Mapping', Source: 'NIT_NM', Value: 'NIT_NM' },
//{ Key: '<:96:>', Type: 'Mapping', Source: 'OXA_NM', Value: 'OXA_NM' },
//{ Key: '<:97:>', Type: 'Mapping', Source: 'PEN_NM', Value: 'PEN_NM' },
//{ Key: '<:98:>', Type: 'Mapping', Source: 'TZP_NM', Value: 'TZP_NM' },
//{ Key: '<:99:>', Type: 'Mapping', Source: 'QDA_NM', Value: 'QDA_NM' },
//{ Key: '<:100:>', Type: 'Mapping', Source: 'RIF_NM', Value: 'RIF_NM' },
//{ Key: '<:101:>', Type: 'Mapping', Source: 'TEC_NM', Value: 'TEC_NM' },
//{ Key: '<:102:>', Type: 'Mapping', Source: 'TCY_NM', Value: 'TCY_NM' },
//{ Key: '<:103:>', Type: 'Mapping', Source: 'TGC_NM', Value: 'TGC_NM' },
//{ Key: '<:104:>', Type: 'Mapping', Source: 'SXT_NM', Value: 'SXT_NM' },
//{ Key: '<:105:>', Type: 'Mapping', Source: 'VAN_NM', Value: 'VAN_NM' },
//{ Key: '<:106:>', Type: 'Mapping', Source: 'VOR_NM', Value: 'VOR_NM' }

                                //'AMC_ND20':'<:46:>',
                                //'AMP_ND10':'<:47:>',
                                //'FEP_ND30':'<:48:>',
                                //'FOX_ND30':'<:49:>',
                                //'CPD_ND10':'<:50:>',
                                //'CAZ_ND30':'<:51:>',
                                //'CRO_ND30':'<:52:>',
                                //'CHL_ND30':'<:53:>',
                                //'CIP_ND5':'<:54:>',
                                //'CLI_ND2':'<:55:>',
                                //'DOX_ND30':'<:56:>',
                                //'ERY_ND15':'<:57:>',
                                //'GEN_ND10':'<:58:>',
                                //'MEM_ND10':'<:59:>',
                                //'NIT_ND300':'<:60:>',
                                //'OXA_ND1':'<:61:>',
                                //'PEN_ND10':'<:62:>',
                                //'RIF_ND5':'<:63:>',
                                //'TCY_ND30':'<:64:>',
                                //'SXT_ND1_2':'<:65:>',
                                //'VAN_ND30':'<:66:>',
                                //'AZM_NE':'<:67:>',
                                //'CRO_NE':'<:68:>',
                                //'CIP_NE':'<:69:>',
                                //'PEN_NE':'<:70:>',
                                //'SXT_NE':'<:71:>',
                                //'VAN_NE':'<:72:>',
                                //'AMC_NM':'<:73:>',
                                //'AMB_NM':'<:74:>',
                                //'AMP_NM':'<:75:>',
                                //'ATM_NM':'<:76:>',
                                //'CAS_NM':'<:77:>',
                                //'CZO_NM':'<:78:>',
                                //'FEP_NM':'<:79:>',
                                //'CTX_NM':'<:80:>',
                                //'CRO_NM':'<:81:>',
                                //'CHL_NM':'<:82:>',
                                //'CIP_NM':'<:83:>',
                                //'CLI_NM':'<:84:>',
                                //'ETP_NM':'<:85:>',
                                //'ERY_NM':'<:86:>',
                                //'FLU_NM':'<:87:>',
                                //'GEN_NM':'<:88:>',
                                //'IPM_NM':'<:89:>',
                                //'LVX_NM':'<:90:>',
                                //'LNZ_NM':'<:91:>',
                                //'MEM_NM':'<:92:>',
                                //'MIF_NM':'<:93:>',
                                //'MFX_NM':'<:94:>',
                                //'NIT_NM':'<:95:>',
                                //'OXA_NM':'<:96:>',
                                //'PEN_NM':'<:97:>',
                                //'TZP_NM':'<:98:>',
                                //'QDA_NM':'<:99:>',
                                //'RIF_NM':'<:100:>',
                                //'TEC_NM':'<:101:>',
                                //'TCY_NM':'<:102:>',
                                //'TGC_NM':'<:103:>',
                                //'SXT_NM':'<:104:>',
                                //'VAN_NM':'<:105:>',
                                //'VOR_NM':'<:106:>'























//{ Key: '<:46:>', Type: 'Mapping', Source: 'CAZ_ND30', Value: 'CAZ_ND30' },
//{ Key: '<:47:>', Type: 'Mapping', Source: 'CIP_ND5', Value: 'CIP_ND5' },
//{ Key: '<:48:>', Type: 'Mapping', Source: 'CRO_ND30', Value: 'CRO_ND30' },
//{ Key: '<:49:>', Type: 'Mapping', Source: 'GEN_ND10', Value: 'GEN_ND10' },
//{ Key: '<:50:>', Type: 'Mapping', Source: 'MEM_ND10', Value: 'MEM_ND10' },
//{ Key: '<:51:>', Type: 'Mapping', Source: 'SXT_ND1', Value: 'SXT_ND1' },
//{ Key: '<:52:>', Type: 'Mapping', Source: 'TCY_ND30', Value: 'TCY_ND30' },
//{ Key: '<:53:>', Type: 'Mapping', Source: 'CHL_ND30', Value: 'CHL_ND30' },
//{ Key: '<:54:>', Type: 'Mapping', Source: 'CLI_ND2', Value: 'CLI_ND2' },
//{ Key: '<:55:>', Type: 'Mapping', Source: 'ERY_ND15', Value: 'ERY_ND15' },
//{ Key: '<:56:>', Type: 'Mapping', Source: 'AMP_NM', Value: 'AMP_NM' },
//{ Key: '<:57:>', Type: 'Mapping', Source: 'CHL_NM', Value: 'CHL_NM' },
//{ Key: '<:58:>', Type: 'Mapping', Source: 'CLI_NM', Value: 'CLI_NM' },
//{ Key: '<:59:>', Type: 'Mapping', Source: 'CRO_NM', Value: 'CRO_NM' },
//{ Key: '<:60:>', Type: 'Mapping', Source: 'CTX_NM', Value: 'CTX_NM' },
//{ Key: '<:62:>', Type: 'Mapping', Source: 'ERY_NM', Value: 'ERY_NM' },
//{ Key: '<:63:>', Type: 'Mapping', Source: 'LNZ_NM', Value: 'LNZ_NM' },
//{ Key: '<:64:>', Type: 'Mapping', Source: 'PEN_ND10', Value: 'PEN_ND10' },
//{ Key: '<:65:>', Type: 'Mapping', Source: 'VAN_NE', Value: 'VAN_NE' }



//                                'PEN_ND10':'<:64:>',
//                                'ERY_ND15':'<:55:>',
//                                'TCY_ND30':'<:52:>',
//                                'CHL_ND30':'<:53:>',
//                                'NIT_ND300':'',
//                                'SSS_ND200':'',
//                                'TOB_ND10':'',
//                                'CLI_ND2':'<:54:>',
//                                'CEP_ND30':'',
//                                'AMP_ND10':'',
//                                'AMK_ND30':'',
//                                'OXA_ND1':'',
//                                'GEN_ND10':'<:49:>',
//                                'CRB_ND100':'',
//                                'VAN_ND30':'',
//                                'SXT_ND1_2':'<:51:>',
//                                'FOX_ND30':'',
//                                'OFX_ND5':'',
//                                'CTX_ND30':'',
//                                'PIP_ND100':'',
//                                'CAZ_ND30':'<:46:>',
//                                'IPM_ND10':'',
//                                'CZX_ND30':'',
//                                'AMC_ND20':'',
//                                'TCC_ND75':'',
//                                'CXM_ND30':'',
//                                'MEZ_ND75':'',
//                                'CIP_ND5':'<:47:>',
//                                'NOR_ND10':'',
//                                'ATM_ND30':'',
//                                'MAN_ND30':'',
//                                'TIC_ND75':'',
//                                'RIF_ND5':'',
//                                'DOX_ND30':'',
//                                'MNO_ND30':'',
//                                'TEC_ND30':'',
//                                'NOV_ND5':'',
//                                'PEN_NM':'',
//                                'CTX_NM':'<:60:>',
//                                'VAN_NM':'',
//                                'PEN_NE':'',
//                                'CTX_NE':'',
//                                'VAN_NE':'<:65:>'
