INSERT INTO ListItem
(Id, ListId, Value, ParentId, LastModifiedDate, Fixed, Enabled, DisplayOrder, Deleted)
VALUES 
( 2001, 77, 'E.coli & C.koseri', null, now(), false, true, 1, false),
( 2002, 77, 'E.coli & Klebsiella spp. (- aerogenes)', null, now(), false, true, 1, false),
( 2003, 77, 'E.coli, K.pneumoniae & P.mirabilis', null, now(), false, true, 1, false),
( 2004, 77, 'E.coli, Klebsiella spp. (- aerogenes) & P.mirabilis', null, now(), false, true, 1, false),
( 2005, 77, 'E.coli, Klebsiella spp. (- aerogenes), Raoultella spp. & P.mirabilis', null, now(), false, true, 1, false),
( 2006, 77, 'E.coli, Citrobacter spp., Klebsiella spp., Raoultella spp., Enterobacter spp. & P.mirabilis', null, now(), false, true, 1, false),
( 2007, 77, 'Enterobacterales (- Morganellaceae)', null, now(), false, true, 1, false),
( 2008, 77, 'Pseudomonas spp. (- aeruginosa)', null, now(), false, true, 1, false),
( 2009, 77, 'S.pseudintermedius, S.schleiferi & S.coagulans', null, now(), false, true, 1, false),
( 2010, 77, 'S.aureus & Coagulase-Negative Staphylococci (- epidermidis & lugdunensis)', null, now(), false, true, 1, false),
( 2011, 77, 'S.epidermidis & S.lugdunensis', null, now(), false, true, 1, false),
( 2012, 77, 'Coagulase-Negative Staphylococci', null, now(), false, true, 1, false),
( 2013, 77, 'Streptococcus Groups A, B, C & G', null, now(), false, true, 1, false),
( 2014, 77, 'Streptococcus Group B', null, now(), false, true, 1, false),
( 2015, 77, 'Viridans Group Streptococci', null, now(), false, true, 1, false),
( 2016, 77, 'S.anginosus Group', null, now(), false, true, 1, false),
( 2017, 77, 'Campylobacter jejuni & coli', null, now(), false, true, 1, false),
( 2018, 77, 'Corynebacterium spp. (- diphtheriae & ulcerans)', null, now(), false, true, 1, false),
( 2019, 77, 'Corynebacterium diphtheriae & ulcerans', null, now(), false, true, 1, false),
( 2020, 77, 'Aerococcus sanguinicola & urinae', null, now(), false, true, 1, false),
( 2021, 77, 'Enterobacterales (- Salmonella spp.)', null, now(), false, true, 1, false),
( 2022, 77, 'Acinetobacter baumannii complex', null, now(), false, true, 1, false),
( 2023, 77, 'Burkholderia cepacia complex', null, now(), false, true, 1, false),
( 2024, 77, 'Other non-Enterobacterales (M100, Table 2B-5)', null, now(), false, true, 1, false),
( 2025, 77, 'S.aureus & S.lugdunensis', null, now(), false, true, 1, false),
( 2026, 77, 'S.pseudintermedius & S.schleiferi', null, now(), false, true, 1, false),
( 2027, 77, 'Staphylococcus spp. (- aureus, lugdunensis, epidermadis, pseudintermedius & schleiferi)', null, now(), false, true, 1, false),
( 2028, 77, 'Staphylococcus spp. (- aureus)', null, now(), false, true, 1, false),
( 2029, 77, 'Enterococcus spp. (- faecium)', null, now(), false, true, 1, false),
( 2030, 77, 'H. influenzae & H. parainfluenzae', null, now(), false, true, 1, false),
( 2031, 77, 'Beta-Hemolytic Streptococci', null, now(), false, true, 1, false),
( 2032, 77, 'S.pyogenes, S.agalactiae & S.dysgalactiae', null, now(), false, true, 1, false),
( 2033, 77, 'Anaerobes', null, now(), false, true, 1, false),
( 2034, 77, 'Abiotrophia spp. & Granulicatella spp.', null, now(), false, true, 1, false),
( 2035, 77, 'HACEK Group', null, now(), false, true, 1, false),
( 2036, 77, 'HACEK Group (- Aggregatibacter spp.)', null, now(), false, true, 1, false),
( 2037, 77, 'Vibrio spp. (- cholerae)', null, now(), false, true, 1, false),
( 2038, 77, 'Burkholderia mallei & Burkholderia pseudomallei', null, now(), false, true, 1, false),
( 2039, 77, 'Francisella tularensis & Brucella spp.', null, now(), false, true, 1, false),
( 2040, 77, 'Bacillus anthracis & Brucella spp.', null, now(), false, true, 1, false),
( 2041, 77, 'Burkholderia mallei, Burkholderia pseudomallei & Yersinia pestis', null, now(), false, true, 1, false),
( 2042, 77, 'Burkholderia pseudomallei & Yersinia pestis', null, now(), false, true, 1, false),
( 2043, 77, 'Salmonella enterica Typhi Group', null, now(), false, true, 1, false),
( 2044, 77, 'Escherichia coli & Proteus mirabilis', null, now(), false, true, 1, false),
( 2045, 77, 'Klebsiella spp. (- aerogenes) & Raoultella spp.', null, now(), false, true, 1, false),
( 2046, 77, 'Enterobacter spp., Klebsiella aerogenes, Citrobacter freundii & Hafnia alvei', null, now(), false, true, 1, false),
( 2047, 77, 'Serratia spp., Morganella morganii & Providencia spp.', null, now(), false, true, 1, false),
( 2048, 77, 'Enterobacter spp., Klebsiella aerogenes, Citrobacter freundii, Serratia spp., Morganella morganii, Hafnia alvei & Providencia spp.', null, now(), false, true, 1, false),
( 2049, 77, 'Escherichia coli, Klebsiella spp. (- aerogenes) & Raoultella spp.', null, now(), false, true, 1, false),
( 2050, 77, 'Serratia spp., Providencia spp., Proteus spp. & Morganella morganii', null, now(), false, true, 1, false),
( 2051, 77, 'Enterococcus faecalis & Enterococcus faecium', null, now(), false, true, 1, false),
( 2052, 77, 'Corynebacterium spp. (- diphtheriae)', null, now(), false, true, 1, false);

ALTER SEQUENCE listitem_id_seq RESTART WITH 10000;
