using arc.app;
using arc.app.Actions;
using arc.app.Admission;
using arc.app.Alert;
using arc.app.Alert.AlertDefinitions;
using arc.app.Asset;
using arc.app.AST;
using arc.app.Barcodes;
using arc.app.Coding;
using arc.app.ExpertRule;
using arc.app.Common;
using arc.app.Common.Display;
using arc.app.Config;
using arc.app.Config.Validation;
using arc.app.Config.Barcode;
using arc.app.Config.Events;
using arc.app.Config.Forms;
using arc.app.Config.Graphs;
using arc.app.Config.Language;
using arc.app.Config.Mapper;
using arc.app.Config.Pages;
using arc.app.Config.Queries;
using arc.app.Config.Reports;
using arc.app.Config.Reports.DataSection;
using arc.app.Config.Reports.SectionFormats;
using arc.app.Config.UIEvents;
using arc.app.Config.Views.DiaryViews;
using arc.app.Config.Views.ReportingGrid;
using arc.app.Config.Workflows;
using arc.app.Configuration;
using arc.app.Configuration.Export;
using arc.app.Configuration.Mappers;
using arc.app.Configuration.Queries;
using arc.app.Exports;
using arc.app.Exports.Formatters;
using arc.app.Graph;
using arc.app.Images;
using arc.app.Import;
using arc.app.Instruments;
using arc.app.Instruments.CustomImport;
using arc.app.Laboratory;
using arc.app.Language;
using arc.app.Location;
using arc.app.Monitoring;
using arc.app.Patient;
using arc.app.Quality;
using arc.app.Reports;
using arc.app.Reports.InclusionSelectors;
using arc.app.Request;
using arc.common.Models.Reports.ReportDesigner;
using arc.domain.Configuration.ReportsConfig;
using arc.app.Roles;
using arc.app.Security;
using arc.app.Settings;
using arc.app.Settings.SettingProviders;
using arc.app.Specification;
using arc.app.Specimen;
using arc.app.SystemConfig;
using arc.app.Tests;
using arc.common;
using arc.common.Data;
using arc.common.Mappers.AST;
using arc.common.Mappers.Instrument;
using arc.common.Models.Alert;
using arc.common.Models.AST;
using arc.common.Models.Coding;
using arc.common.Models.Config;
using arc.common.Models.Export;
using arc.common.Models.Instruments;
using arc.common.Utils;
using arc.data;
using arc.data.Admission;
using arc.data.Alert;
using arc.data.Asset;
using arc.data.Coding;
using arc.data.Coding.TestPatterns;
using arc.data.Common;
using arc.data.Configuration;
using arc.data.EventData;
using arc.data.Exports;
using arc.data.Import;
using arc.data.Graph;
using arc.data.Images;
using arc.data.Instruments;
using arc.data.Location;
using arc.data.model.Culture;
using arc.data.model.Instruments;
using arc.data.Organisation;
using arc.data.Patient;
using arc.data.Quality;
using arc.data.Reports;
using arc.data.Request;
using arc.data.Security;
using arc.data.Security.Token;
using arc.data.Specification;
using arc.data.Specimen;
using arc.data.AST;
using arc.data.SystemConfig;
using arc.data.Tests;
using arc.data.Utils;
using arc.domain.Alert;
using arc.domain.Coding;
using arc.domain.Configuration.EventsConfig;
using arc.domain.Configuration.QueryConfig;
using arc.identity;
using Microsoft.Extensions.DependencyInjection;
using arc.app.Reports.ReportDesigner;
using arc.app.Files;

namespace arc.api.StartUpOptions
{
    public static class ServicesToInject
    {
        public static IServiceCollection AddCommon(this IServiceCollection services)
        {
            services.AddTransient<IAccessionNumberCalculator, AccessionNumberCalculator>();
            services.AddTransient<IActionHandler, ActionHandler>();
            services.AddTransient<IACKReceiptLoader, ACKReceiptLoader>();
            services.AddTransient<IAddRoleDataHandler, AddRoleDataHandler>();
            services.AddTransient<IAddTopLevelItemsToMenuPermissions, AddTopLevelItemsToMenuPermissions>();
            services.AddTransient<IEnsureMandatoryMenuPermissions, EnsureMandatoryMenuPermissions>();
            services.AddTransient<IAlertHandler, AlertHandler>();
            services.AddTransient<IAlertMessageHandler, AlertMessageHandler>();
            services.AddTransient<IAlertProcessor, AlertProcessor>();
            services.AddTransient<IAllowedButtonWorkflowStates, AllowedButtonWorkflowStates>();
            services.AddTransient<IASTHandler, ASTHandler>();
            services.AddTransient<IExpertRulePageDisplayService, ExpertRulePageDisplayService>();
            services.AddTransient<IExpertRuleAstActionBuilder, ExpertRuleAstActionBuilder>();
            services.AddTransient<ISpecialConsiderationEnricher, SpecialConsiderationEnricher>();
            services.AddTransient<IBarcodesHandler, BarcodesHandler>();
            services.AddTransient<IBatchEventHandler, BatchEventHandler>();
            services.AddTransient<IBatchPrintHandler, BatchPrintHandler>();
            services.AddTransient<IBreakpointHandler, BreakpointHandler>();
            services.AddTransient<ICraftedUtils, CraftedUtils>();
            services.AddTransient<ICommentSelector, CommentSelector>();
            services.AddTransient<IConfigFactoryProcessor, ConfigFactoryProcessor>();
            services.AddTransient<IConfigItemHandler, ConfigItemHandler>();
            services.AddTransient<IConfigListDataHandler, ConfigListDataHandler>();
            services.AddTransient<IConfigListUtils, ConfigListUtils>();
            services.AddTransient<IListViewTestsValidator, ListViewTestsValidator>();
            services.AddScoped<IConfigCache, ConfigCache>();
            services.AddTransient<IConfigHandler, ConfigHandler>();
            services.AddTransient<IConfigTransferHandler, ConfigTransferHandler>();
            services.AddTransient<IConfigUpdater, ConfigUpdater>();
            services.AddTransient<IControllerUtils, ControllerUtils>();
            services.AddTransient<IConvertJsonStructureToKeyValuePair, ConvertJsonStructureToKeyValuePair>();
            services.AddTransient<IConvertJsonStructureToPipeSeparatedList, ConvertJsonStructureToPipeSeparatedList>();
            services.AddTransient<ICopyFormConfiguration, CopyFormConfiguration>();
            services.AddTransient<ICopyProperties, CopyProperties>();
            services.AddTransient<ICultureDetailsSelector, CultureDetailsSelector>();
            services.AddTransient<ICultureHandler, CultureHandler>();
            services.AddTransient<ICultureList, CultureList>();
            services.AddTransient<ICultureSelector, CultureSelector>();
            services.AddTransient<ICultureTestOnlyAlerts, CultureTestOnlyAlerts>();
            services.AddTransient<ICurrentRoleDetailsHandler, CurrentRoleDetailsHandler>();
            services.AddTransient<IDataRuleValidator, DataRuleValidator>();
            services.AddTransient<IDataSectionAdapter, DataSectionAdapter>();
            services.AddTransient<IDirectTestOnlyAlerts, DirectTestOnlyAlerts>();
            services.AddTransient<IDirectTestAndCultureTestAlerts, DirectTestAndCultureTestAlerts>();
            services.AddTransient<IDirectTestSelector, DirectTestSelector>();
            services.AddTransient<IEventPermissionHandler, EventPermissionHandler>();
            services.AddTransient<IExpertRuleHandler, ExpertRuleHandler>();
            services.AddTransient<IExportConfigurationProcessor, ExportConfigurationProcessor>();
            services.AddTransient<IExportDocumentBuilder, ExportDocumentBuilder>();
            services.AddTransient<IExportFormatWriterFactory, ExportFormatWriterFactory>();
            services.AddTransient<IExportHandler, ExportHandler>();
            services.AddTransient<IExportPostQueryProcessor, ExportPostQueryProcessor>();
            services.AddTransient<IExportProfileConfigHandler, ExportProfileConfigHandler>();
            services.AddTransient<IExportProfileQueryHandler, ExportProfileQueryHandler>();
            services.AddTransient<IExportProfileMappingFieldOptionBuilder, ExportProfileMappingFieldOptionBuilder>();
            services.AddTransient<IExportProfileMappingHandler, ExportProfileMappingHandler>();
            services.AddTransient<IExportProfileMappingValidator, ExportProfileMappingValidator>();
            services.AddTransient<IExportRunHandler, ExportRunHandler>();
            services.AddTransient<IExistingFieldCatalogue, ExistingFieldCatalogue>();
            services.AddTransient<IFieldConfigUtils, FieldConfigUtils>();
            services.AddTransient<IFieldListHandler, FieldListHandler>();
            services.AddTransient<IFieldTypeList, FieldTypeList>();
            services.AddTransient<IFormattedCultureTestList, FormattedCultureTestList>();
            services.AddTransient<IFormattedJsonQueryHandler, FormattedJsonQueryHandler>();
            services.AddTransient<IQueueListQueryHandler, QueueListQueryHandler>();
            services.AddTransient<IFormHandler, FormHandler>();
            services.AddTransient<IFormConfigDefinition, FormConfigDefinition>();
            services.AddTransient<IFormConfigList, FormConfigList>();
            services.AddTransient<IGetListsConfiguration, GetListsConfiguration>();
            services.AddScoped<ICacheManager, CacheManager>();
            services.AddTransient<IConfigExtractionUtils, ConfigExtractionUtils>();
            services.AddTransient<IGenerateMoreData, GenerateMoreData>();
            services.AddTransient<IDataModelColumnResolver, DataModelColumnResolver>();
            services.AddTransient<IFormPageTableRoutingService, FormPageTableRoutingService>();
            services.AddTransient<IHandleConfig, HandleConfig>();
            services.AddTransient<IHandleEvent, HandleEvent>();
            services.AddTransient<IHandleList, HandleList>();
            services.AddTransient<IHandleQuery, HandleQuery>();
            services.AddTransient<IInstrumentInterfaceHandler, InstrumentInterfaceHandler>();
            services.AddTransient<IInstrumentManualRequestService, InstrumentManualRequestService>();
            services.AddTransient<IInstrumentRequestHandler, InstrumentRequestHandler>();
            services.AddTransient<IInstrumentResultHandler, InstrumentResultHandler>();
            services.AddTransient<ICustomImportRecordParser, CustomImportRecordParser>();
            services.AddTransient<IImportValueResolver, ImportValueResolver>();
            services.AddTransient<IUniqueReferenceResolver, UniqueReferenceResolver>();
            services.AddTransient<IInterfaceCriteriaEvaluator, InterfaceCriteriaEvaluator>();
            services.AddTransient<ICustomImportHandler, CustomImportHandler>();
            services.AddTransient<IJsonDataFormatter, JsonDataFormatter>();
            services.AddTransient<IJsonDisplayRootResolver, JsonDisplayRootResolver>();
            services.AddTransient<IJsonDisplaySectionBuilder, JsonDisplaySectionBuilder>();
            services.AddTransient<IDisplayValueResolverFactory, DisplayValueResolverFactory>();
            services.AddTransient<IDisplayValueResolver, ListDisplayValueResolver>();
            services.AddTransient<IDisplayValueResolver, OrganisationDisplayValueResolver>();
            services.AddTransient<IDisplayValueResolver, OrganismDisplayValueResolver>();
            services.AddTransient<IDisplayValueResolver, AntibioticDisplayValueResolver>();
            services.AddTransient<IDisplayValueResolver, ExpertRuleDisplayValueResolver>();
            services.AddTransient<IDisplayValueResolver, TestPatternDisplayValueResolver>();
            services.AddTransient<IDisplayValueResolver, BreakpointSpecificationDisplayValueResolver>();
            services.AddTransient<IDisplayValueResolver, AstMeasurementDisplayValueResolver>();
            services.AddTransient<ITestResultsForListFormatter, TestResultsForListFormatter>();
            services.AddTransient<IJsonElementRemover, JsonElementRemover>();
            services.AddTransient<IJsonUtils, JsonUtils>();
            services.AddTransient<IJsonMapper, JsonMapper>();
            services.AddTransient<IJsonReplacer, JsonReplacer>();
            services.AddTransient<IJsonFieldsCollector, JsonFieldsCollector>();
            services.AddTransient<IJsonWholeStructureFieldsCollector, JsonWholeStructureFieldsCollector>();
            services.AddTransient<IApplicableIsolateTestsResolver, ApplicableIsolateTestsResolver>();
            services.AddTransient<ICultureTestSelectionFilter, CultureTestSelectionFilter>();
            services.AddTransient<ILaboratoryConfigurationHandler, LaboratoryConfigurationHandler>();
            services.AddTransient<ILanguageHandler, LanguageHandler>();
            services.AddTransient<ILanguageListHandler, LanguageListHandler>();
            services.AddTransient<IListFieldUtils, ListFieldUtils>();
            services.AddTransient<IListFilterHandler, ListFilterHandler>();
            services.AddTransient<ILocalFieldResolver, LocalFieldResolver>();
            services.AddTransient<ILoginCommandHandler, LoginCommandHandler>();
            services.AddScoped<ILogWriter, LogWriter>();
            services.AddTransient<IMapObjectArrayToJson, MapObjectArrayToJson>();
            services.AddTransient<IMenuPermissionHandler, MenuPermissionHandler>();
            services.AddTransient<IMessageQueue, MessageQueue>();
            services.AddTransient<IOrganismExistsAlerts, OrganismExistsAlerts>();
            services.AddTransient<IOrganismASTTestAlerts, OrganismASTTestAlerts>();
            services.AddTransient<IOrganismTestAlerts, OrganismTestAlerts>();
            services.AddTransient<IOrganismTestsASTTestAlerts, OrganismTestsASTTestAlerts>();
            services.AddTransient<IPasswordUtils, PasswordUtils>();
            services.AddTransient<PatientSearchPostMappingHandler>();
            services.AddTransient<IAgeDisplayQueryResultEnricher, AgeDisplayQueryResultEnricher>();
            services.AddTransient<IPermissionHandler, PermissionHandler>();
            services.AddTransient<IPreferenceHandler, PreferenceHandler>();
            services.AddTransient<IProcessMapping, ProcessMapping>();
            services.AddTransient<IProfileListHandler, ProfileListHandler>();
            services.AddTransient<IQueryPermissions, QueryPermissions>();
            services.AddTransient<IIqcTestProfileQueryHandler, IqcTestProfileQueryHandler>();
            services.AddTransient<IRegisterHandler, RegisterHandler>();
            services.AddTransient<IRemoveButtonsWithoutPermission, RemoveButtonsWithoutPermission>();
            services.AddTransient<IReplaceListItemValues, ReplaceListItemValues>();
            services.AddTransient<IReportConfigDefinition, ReportConfigDefinition>();
            services.AddTransient<IReportDesignerHandler, ReportDesignerHandler>();
            services.AddTransient<IReportHeaderFooterUsageService, ReportHeaderFooterUsageService>();
            services.AddTransient<IReportTranslator, ReportTranslator>();
            services.AddTransient<IReportHandler, ReportHandler>();
            services.AddTransient<IReportStatusMapper, ReportStatusMapper>();
            services.AddTransient<IRunEventHandler, RunEventHandler>();
            services.AddTransient<IRunIqcTestHandler, RunIqcTestHandler>();
            services.AddTransient<IEditIqcResultHandler, EditIqcResultHandler>();
            services.AddTransient<IReportInclusionSelector, ReportInclusionSelector>();
            services.AddTransient<IResetNamesInForm, ResetNamesInForm>();
            services.AddTransient<ISetupHandler, SetupHandler>();
            services.AddTransient<ISingleInstrumentProfile, SingleInstrumentProfile>();
            services.AddTransient<ISpecimenEventListQuery, SpecimenEventListQuery>();
            services.AddTransient<arc.app.Laboratory.ISpecimenListTatEnricher, arc.app.Laboratory.SpecimenListTatEnricher>();
            services.AddTransient<arc.app.ExpertRule.IExpertRuleTestConditionListDisplayEnricher, arc.app.ExpertRule.ExpertRuleTestConditionListDisplayEnricher>();
            services.AddTransient<ISpecimenRecordHandler, SpecimenRecordHandler>();
            services.AddTransient<ISpecimenRecordReportHandler, SpecimenRecordReportHandler>();
            services.AddTransient<ISpecimenRecordUtils, SpecimenRecordUtils>();
            services.AddTransient<ISqlCommand, SqlCommand>();
            services.AddTransient<ISqlQuery, SqlQuery>();
            services.AddTransient<IStateHandler, StateHandler>();
            services.AddTransient<IStandardFilters, StandardFilters>();
            services.AddTransient<IStandardSpecimenAlerts, StandardSpecimenAlerts>();
            services.AddTransient<ITableEntryHandler, TableEntryHandler>();
            services.AddTransient<ITestNameInterpreter, TestNameInterpreter>();
            services.AddTransient<ITestForReport, TestForReport>();
            services.AddTransient<ITestPatternHandler, TestPatternHandler>();
            services.AddTransient<ITestSelectionHandler, TestSelectionHandler>();
            services.AddTransient<ITokenHandler, TokenHandler>();
            services.AddTransient<IViewHandler, ViewHandler>();
            services.AddTransient<IWorkflowDesignerHandler, WorkflowDesignerHandler>();
            services.AddTransient<IWorkflowFinder, WorkflowFinder>();
            services.AddTransient<IWhonetAntibioticColumns, WhonetAntibioticColumns>();
            services.AddTransient<IWorkflowHandler, WorkflowHandler>();

            return services;
        }

        public static IServiceCollection AddFactories(this IServiceCollection services)
        {
            services.AddTransient<ISettingProviderFactory, SettingProviderFactory>();
            services.AddTransient<IActionFactory, ActionFactory>();
            services.AddTransient<IAllBaseViewConfigFactory, AllBaseViewConfigFactory>();
            services.AddTransient<IBarcodePrintConfigFactory, BarcodePrintConfigFactory>();
            services.AddTransient<IConfigFactory, ConfigFactory>();
            services.AddTransient<IDataListFactory, DataListFactory>();
            services.AddTransient<IDataSectionFactory, DataSectionFactory>();
            services.AddTransient<IDiaryFactory, DiaryFactory>();
            services.AddTransient<IEventFactory, EventFactory>();
            services.AddTransient<IFormConfigFactory, FormConfigFactory>();
            services.AddTransient<IGraphFactory, GraphFactory>();
            services.AddTransient<IGraphConfigFactory, GraphConfigFactory>();
            services.AddTransient<IInstrumentFactory, InstrumentFactory>();
            services.AddTransient<ILanguageFactory, LanguageFactory>();
            services.AddTransient<IListConfigFactory, ListConfigFactory>();
            services.AddTransient<IListViewConfigFactory, ListViewConfigFactory>();
            services.AddTransient<IMapperFactory, MapperFactory>();
            services.AddTransient<IPageConfigFactory, PageConfigFactory>();
            services.AddTransient<IPostParameterMappingHandlerFactory, PostParameterMappingHandlerFactory>();
            services.AddTransient<ISectionFormatFactory, SectionFormatFactory>();
            services.AddTransient<IQueryFactory, QueryFactory>();
            services.AddTransient<IQueryHandlerFactory, QueryHandlerFactory>();
            services.AddTransient<IReportFactory, ReportFactory>();
            services.AddTransient<IRecordViewConfigFactory, RecordViewConfigFactory>();
            services.AddTransient<IReportingGridFactory, ReportingGridFactory>();
            services.AddTransient<ISpecialFactory, SpecialFactory>();
            services.AddTransient<ISpecialEventFactory, SpecialEventFactory>();
            services.AddTransient<ISpecialQueryFactory, SpecialQueryFactory>();
            services.AddTransient<ISpecialValidationFactory, SpecialValidationFactory>();
            services.AddTransient<ISpecialMappingFactory, SpecialMappingFactory>();
            services.AddTransient<IUIEventConfigFactory, UIEventConfigFactory>();
            services.AddTransient<IWorkflowConfigFactory, WorkflowConfigFactory>();

            return services;
        }

        public static IServiceCollection AddSqlRepositories(this IServiceCollection services)
        {
            services.AddTransient<IAdmissionRepository, AdmissionRepository>();
            services.AddTransient<IAlertRepository, AlertRepository>();
            services.AddTransient<IAntibioticRepository, AntibioticRepository>();
            services.AddTransient<IASTRepository, ASTRepository>();
            services.AddTransient<IAstSusceptibilityOverrideRepository, AstSusceptibilityOverrideRepository>();
            services.AddTransient<IBreakpointRepository, BreakpointRepository>();
            services.AddTransient<ICodingRepository, CodingRepository>();
            services.AddTransient<ICommentRepository, CommentRepository>();
            services.AddTransient<IConfigRepository, ConfigRepository>();
            services.AddTransient<ICultureRepository, CultureRepository>();
            services.AddTransient<ICustomImportRepository, CustomImportRepository>();
            services.AddTransient<IExpertRuleRepository, ExpertRuleRepository>();
            services.AddTransient<IExportProfileRepository, ExportProfileRepository>();
            services.AddTransient<IExportProfileMappingRepository, ExportProfileMappingRepository>();
            services.AddTransient<IExportProfileFieldRepository, ExportProfileFieldRepository>();
            services.AddTransient<IExportRepository, ExportRepository>();
            services.AddTransient<IExportRunHistoryRepository, ExportRunHistoryRepository>();
            services.AddTransient<IExportScheduleRepository, ExportScheduleRepository>();
            services.AddTransient<IFormConfigRepository, FormConfigRepository>();
            services.AddTransient<IFileHandler, FileHandler>();
            services.AddTransient<IGeneralRepository, GeneralRepository>();
            services.AddTransient<IGenericRepository, SqlGenericRepository>();
            services.AddTransient<IGraphRepository, GraphRepository>();
            services.AddTransient<IJsonConfigRepository, JsonConfigRepository>();
            services.AddTransient<IImageRepository, ImageRepository>();
            services.AddTransient<IInstrumentErrorRepository, InstrumentErrorRepository>();
            services.AddTransient<IInstrumentRepository, InstrumentRepository>();
            services.AddTransient<ILaboratoryRepository, LaboratoryRepository>();
            services.AddTransient<ILaboratoryConfigRepository, LaboratoryConfigRepository>();
            services.AddTransient<ILanguageRepository, LanguageRepository>();
            services.AddTransient<ILocationRepository, LocationRepository>();
            services.AddTransient<ILoginRepository, SqlGenericRepository>();
            services.AddTransient<IQueueHashService, QueueHashService>();
            services.AddTransient<IMessageRepository, MessageRepository>();
            services.AddTransient<IMoreDataRepository, MoreDataRepository>();
            services.AddTransient<IRepository<EventConfig>, EventRepository>();
            services.AddTransient<IListRepository, ListRepository>();
            services.AddTransient<IOrganisationRepository, OrganisationRepository>();
            services.AddTransient<IOrganismRepository, OrganismRepository>();
            services.AddTransient<IPatientRepository, PatientRepository>();
            services.AddTransient<IQualityRepository, QualityRepository>();
            services.AddTransient<IReportRepository, ReportRepository>();
            services.AddTransient<IReportConfigRepository, ReportConfigRepository>();
            services.AddTransient<IRepository<QueryConfig>, QueryConfigRepository>();
            services.AddTransient<IRequestRepository, RequestRepository>();
            services.AddTransient<IRoleRepository, RoleRepository>();
            services.AddTransient<ISpecimenRepository, SpecimenRepository>();
            services.AddTransient<ISpecificationRepository, SpecificationRepository>();
            services.AddTransient<ISetupRespository, SqlSetupRepository>();
            services.AddTransient<ISpecimenAlertRepository, SpecimenAlertRepository>();
            services.AddTransient<IStateRepository, StateRepository>();
            services.AddTransient<IStorageRepository, StorageRepository>();
            services.AddTransient<IReportHistoryRepository, ReportHistoryRepository>();
            services.AddTransient<ITestRepository, TestRepository>();
            services.AddTransient<ITestPatternRepository, TestPatternRepository>();
            services.AddTransient<ITokenRepository, TokenRepository>();
            services.AddTransient<IUserRepository, UserRepository>();
            services.AddTransient<ITopicRepository, TopicRepository>();

            return services;
        }

        public static IServiceCollection AddAdapters(this IServiceCollection services)
        {
            services.AddTransient<IBarcodePrintLabelResolver, BarcodePrintLabelResolver>();
            services.AddTransient<IBarcodePrintConfigAdapter, BarcodePrintConfigAdapter>();
            services.AddTransient<IEventAdapter, EventAdapter>();
            services.AddTransient<IFormConfigAdapter, FormConfigAdapter>();
            services.AddTransient<IMapperAdapter, MapperAdapter>();
            services.AddTransient<IPageConfigAdapter, PageConfigAdapter>();
            services.AddTransient<IQueryAdapter, QueryAdapter>();
            services.AddTransient<IReportAdapter, ReportAdapter>();
            services.AddTransient<IReportFooterAdapter, ReportFooterAdapter>();
            services.AddTransient<IReportHeaderAdapter, ReportHeaderAdapter>();
            services.AddTransient<ISectionAdapter, SectionAdapter>();
            services.AddTransient<ISectionFormatAdapter, SectionFormatAdapter>();
            services.AddTransient<IUIEventConfigAdapter, UIEventConfigAdapter>();
            services.AddTransient<IWorkflowAdapter, WorkflowAdapter>();

            return services;
        }

        public static IServiceCollection AddMappers(this IServiceCollection services)
        {
            services.AddTransient<IAddRoleMapping, AddRoleMapping>();
            services.AddTransient<IMapType<AlertDetails, AlertDetailsModel>, AlertDetailsToAlertDetailsModelMapper>();
            services.AddTransient<IMapType<AlertDetailsModel, AlertDetails>, AlertDetailsModelToAlertDetailsMapper>();
            services.AddTransient<IMapWithList<ASTModel, ASTRowModel>, ASTModelToASTRowModelMapper>();
            services.AddTransient<IMapType<ExpertRule, ExpertRuleDetailsModel>, ExpertRuleToExpertRuleDetailsModelMapper>();
            services.AddTransient<IMapType<ExpertRuleDetailsModel, ExpertRule>, ExpertRuleDetailsModelToExpertRuleMapper>();
            services.AddTransient<IMapWithList<ExpertRuleActionReturnModel, ASTRowModel>, ExpertRuleActionReturnModelToASTRowModelMapper>();
            services.AddTransient<IMapType<ReportSectionConfig, SectionModel>, ReportSectionConfigToSectionModelMapper>();
            services.AddTransient<IMapType<ResponseModel, InstrumentResultsDataModel>, ResponseModelToInstrumentResultsDataModelMapper>();
            services.AddTransient<IMapType<ResponseModel, CultureDataModel>, ResponseModelToCultureDataModelMapper>();
            services.AddTransient<IMapType<SectionModel, ReportSectionConfig>, SectionModelToReportSectionConfigMapper>();
            services.AddTransient<IMapWithList<SusceptibilityModel, ASTRowModel>, SusceptibilityModelToASTRowModelMapper>();
            services.AddTransient<IMapType<TestPatternModel, TestPattern>, TestPatternModelToTestPatternMapper>();
            services.AddTransient<IMapType<(ReportConfig reportConfig, ViewInfo viewInfo), ReportDesignerModel>, ReportConfigToReportDesignerModelMapper>();
            services.AddTransient<IMapType<ReportSectionConfig, ReportSectionModel>, ReportSectionConfigToReportSectionModelMapper>();
            services.AddTransient<IMapType<ReportSectionFormatConfig, CustomFormatModel>, ReportSectionFormatConfigToCustomFormatModelMapper>();
            services.AddTransient<IMapType<(ReportHeaderFooterConfig config, string sectionType), ReportSectionModel>, ReportHeaderFooterConfigToReportSectionModelMapper>();
            services.AddTransient<IMapWithList<TestPatternLineModel, ASTRowModel>, TestPatternLineModelToASTRowModelMapper>();

            return services;
        }
    }
}
