using arc.app.Common;

namespace arc.app.Config.Pages
{
    /// <summary>
    /// Page definition for adding a new form group.
    /// Rules (RulesEditor) only. New form groups are created empty; fields are assigned via Edit Form Group.
    /// Form group key is auto-generated by the system (fg1, fg2, ...).
    /// </summary>
    internal class AddFormGroupPageConfig : IDefinition
    {
        public string Get()
        {
            var page = @"{
                            name: 'addformgrouppage',
                            pageTitle: '@ConAddFG@',
                            text: '',
                            columns: [
                                {
                                    key: 'col1',
                                    formGroups: [
                                        {
                                            key: 'fg1',
                                            fields: [
                                                { id: 'Rules', type: 'ruleseditor', label: '@GenRul@', context: 'formgroup' }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }";

            return page;
        }
    }
}
