INSERT INTO List
(Id, Name, Grouping, ParentId, Common, Description, LastModifiedDate)
VALUES 
( 1, 'PatientLocation', 'Patient', null, false,'Patient Location', now()),
( 2, 'PatientWard', 'Specimen', null, false, 'Patient Ward', now()),
( 3, 'PatientDiagnosis', 'Specimen', null, true, 'Patient Diagnosis', now()),
( 4, 'SpecimenType', 'Specimen', null, true, 'Specimen Type', now()),
( 5, 'SpecimenSite', 'Specimen', 4, true, 'Specimen Site', now()),
( 6, 'ReceivedCondition', 'Specimen', null, true, 'Received Condition', now()),
( 7, 'SpecimenGuidanceComment', 'Specimen', null, true, 'Culture Guidance Comment', now()),
( 8, 'SpecimenCondition', 'Specimen', null, true, 'Specimen Condition', now()),
( 9, 'SpecimenApiIdPanel', 'Specimen', null, true, 'Specimen Api Id Panel', now()),
( 11, 'SpecimenTestType', 'Specimen', null, false, 'Specimen Test Type', now()),
( 12, 'SpecimenQuantity', 'Specimen', null, true, 'Specimen Quantity', now()),
( 13, 'Gender', 'Patient', null, true, 'Gender', now()),
( 14, 'GraphType', 'Graphs', null, true, 'GraphType', now()),
( 15, 'DateInterval', 'Graphs', null, true, 'DateInterval', now()),
( 17, 'Qualitative','Tests', null, true, 'Qualitative', now()),
( 18, 'Seen', 'Tests', null, true, 'Seen', now()),
( 19, 'Organism', 'Tests', null, false, 'Organism', now()),
( 20, 'AFBQuantity', 'Tests', null, true, 'AFB Quantity', now()),
( 21, 'IndiaInk', 'Tests', null, true, 'India Ink', now()),
( 22, 'IndiaInkResult', 'Tests', null, true, 'India Ink Result', now()),
( 23, 'Pluses', 'Tests', null, true, 'Pluses', now()),
( 24, 'Parasite', 'Tests', null, true, 'Parasite', now()),
( 25, 'ParasiteType', 'Tests', null, true, 'Parasite Type', now()),
( 26, 'Found', 'Tests', null, true, 'Found', now()),
( 27, 'KOHResult', 'Tests', null, true, 'KOH Result', now()),
( 28, 'Fungus', 'Tests', null, true, 'Fungus', now()),
( 29, 'Epithelium', 'Tests', null, true, 'Epithelium', now()),
( 30, 'Auramine', 'Tests', null, false, 'Auramine', now()),
( 31, 'Cast', 'Tests', null, true, 'Cast', now()),
( 32, 'Crystal', 'Tests', null, true, 'Crystal', now()),
( 33, 'WrightsStain', 'Tests', null, true, 'Wrights Stain', now()),
( 50, 'ESBL', 'AST', null, true, 'ESBL', now()),
( 54, 'SpecimenAppearance', 'Specimen', 4, true, 'Specimen Appearance', now()),
( 55, 'ImmediateAction', 'Specimen', null, false, 'Immediate Action', now()),
( 56, 'State', 'Specimen', null, false, 'State', now()),
( 57, 'SubmitSpecimen', 'Specimen', null, false, 'Submit Specimen', now()),
( 58, 'SpecimenApproval', 'Specimen', null, true, 'Specimen Approval', now()),
( 59, 'SpecimenWorkflowList', 'Specimen', null, false, 'Specimen Workflow List', now()),
( 60, 'SpecimenWorkflowItems', 'Specimen', 59, false, 'Specimen Workflow Items', now()),
( 70, 'ExportType', 'Export', null, false, 'Export Type', now()),
( 71, 'BenchReadDay0Action', 'Specimen', null, false, 'Bench Read Day0 Action', now()),
( 72, 'BenchReadDay1Action', 'Specimen', null, false, 'Bench Read Day1 Action', now()),
( 73, 'Topic', 'System', null, false, 'Topic', now()),
( 74, 'Event', 'System', null, false, 'Event', now()),
( 75, 'EventStatus', 'System', null, false, 'Event Status', now()),
( 76, 'Translation', 'System', null, false, 'Translation', now()),
( 77, 'Coding', 'System', null, false, 'Coding', now()),
( 78, 'Host', 'System', null, false, 'Host', now()),
( 79, 'TestMethod', 'System', null, false, 'Test Method', now()),
( 80, 'TestResult', 'System', null, false, 'Test Result', now()),
( 81, 'Gram', 'System', null, true, 'Gram', now()),
( 82, 'AntibioticGroup', 'System', null, false, 'Antibiotic Group', now()),
( 83, 'Pregnancy', 'System', null, true, 'Pregnancy', now()),
( 84, 'ph', 'System', null, true, 'Ph', now()),
( 85, 'SpecificGravity', 'System', null, true, 'Specific Gravity', now()),
( 86, 'ProteinDipstick', 'System', null, true, 'Protein Dipstick', now()),
( 87, 'KetonesDipstick', 'System', null, true, 'Ketones Dipstick', now()),
( 88, 'GlucoseDipstick', 'System', null, true, 'Glucose Dipstick', now()),
( 89, 'BloodDipstick', 'System', null, true, 'Blood Dipstick', now()),
( 90, 'LeucocytesDipstick', 'System', null, true, 'Leucocytes Dipstick', now()),
( 91, 'NitritesDipstick', 'System', null, true, 'Nitrites Dipstick', now()),
( 92, 'HPyloriAntigen', 'System', null, true, 'H. Pylori Antigen', now()),
( 93, 'JEVSerology', 'System', null, true, 'JEV Serology', now()),
( 94, 'Betalactamase', 'System', null, true, 'Betalactamase', now()),
( 95, 'Carbapenemase', 'System', null, true, 'Carbapenemase', now()),
( 96, 'AntibioticsInLast24hrs', 'System', null, true, 'Antibiotics In Last 24hrs', now()),
( 97, 'TempInLast24hrs', 'System', null, true, 'Temp In Last 24hrs', now()),
( 98, 'ReportList', 'System', null, false, 'Report List', now()),
( 99, 'PrintStatus', 'System', null, false, 'Print Status', now()),
( 100, 'Guidelines', 'System', null, true, 'Guidelines', now()),
( 101, 'SpecialConsiderations', 'System', null, true, 'Special Breakpoint Considerations', now()),
( 102, 'CultureType', 'Culture', null, true, 'Culture Type', now()),
( 103, 'AndOr', 'System', null, false, 'And/Or', now()),
( 104, 'AlertType', 'System', null, false, 'Alert Type', now()),
( 105, 'Tag', 'System', null, false, 'Tag', now()),
( 106, 'AlertPosition', 'System', null, false, 'Alert Position', now()),
( 107, 'ApprovalComment', 'Specimen', null, true, 'Approval Comment', now()),
( 108, 'RejectionReasonList', 'Specimen', null, true, 'Rejection Reason', now()),
( 109, 'FieldTypeList', 'System', null, false, 'Field Type List', now()),
( 110, 'YesNo', 'System', null, false, 'Yes No', now()),
( 111, 'GridWidth', 'System', null, false, 'Grid Field Width', now()),
( 112, 'FormatList', 'System', null, false, 'Report Format List', now()),
( 113, 'IqcTestState', 'IqcTests', null, false, 'State', now()),
( 114, 'ActionList', 'System', null, false, 'Action List', now()),
( 115, 'Oxidase', 'System', null, true, 'Oxidase', now()),
( 116, 'Catalase', 'System', null, true, 'Catalase', now()),
( 117, 'AntibiogramType', 'System', null, false, 'AntibiogramType', now()),
( 118, 'LocationLevel', 'System', null, false, 'LocationLevel', now()),
( 119, 'TestStatus', 'System', null, false, 'TestStatus', now()),
( 120, 'YearSetting', 'System', null, true, 'YearSetting', now()),
( 121, 'DrugCategory', 'Specimen', null, true, 'Antibiotic Category', now()),
( 122, 'ASTCannedComments', 'Specimen', null, true, 'AST Canned Comments', now());

ALTER SEQUENCE list_id_seq RESTART WITH 10000;