namespace arc.data.model.Coding;

/// <summary>
/// Represents the fields in the ast table in the database.
/// </summary>
public class AstDataModel : IdAndDateBase
{
    /// <summary>
    /// Gets or sets foreign key linking the culture table to the ast table.
    /// </summary>
    public int? CultureId { get; set; }

    /// <summary>
    /// Gets or sets the type of test.
    /// </summary>
    public string? TestType { get; set; }

    /// <summary>
    /// Gets or sets the entry type.
    /// </summary>
    public string? EntryType { get; set; }

    /// <summary>
    /// Gets or sets foreign key linking the listitem table to the ast table. This links to the testmethod list in the listitem table.
    /// </summary>
    public int? TestMethodId { get; set; }

    /// <summary>
    /// Gets or sets foreign key linking the antibiotic table to the ast table.
    /// </summary>
    public int? AntibioticId { get; set; }

    /// <summary>
    /// Gets or sets the dosage value.
    /// </summary>
    public int? Dosage { get; set; }

    /// <summary>
    /// Gets or sets the measurement value.
    /// </summary>
    public decimal? Measurement { get; set; }

    /// <summary>
    /// Gets or sets foreign key linking the listitem table to the ast table. This links to the susceptibility list in the listitem table.
    /// </summary>
    public int? SusceptibilityId { get; set; }

    /// <summary>
    /// Gets or sets whether the result should be displayed on the report.
    /// </summary>
    public string? DisplayOnReport { get; set; }

    /// <summary>
    /// Gets or sets the MIC comparison value.
    /// </summary>
    public string? MicComparison { get; set; }

    /// <summary>
    /// Gets or sets foreign key linking the breakpoint table to the ast table.
    /// </summary>
    public int? AppliedBreakpointId { get; set; }

    /// <summary>
    /// Gets or sets foreign key linking the listitem table to the ast table. This links to the guidelines list in the listitem table.
    /// </summary>
    public int? GuidelinesId { get; set; }

    /// <summary>
    /// Gets or sets foreign key linking the listitem table to the ast table. This links to the category list in the listitem table.
    /// </summary>
    public int? CategoryId { get; set; }

    /// <summary>
    /// Gets or sets foreign key linking the expertrule table.
    /// Populated when the AST row was generated by an expert rule.
    /// </summary>
    public int? ExpertRuleId { get; set; }

    /// <summary>
    /// Gets or sets whether this row is an expert rule result line.
    /// </summary>
    public bool? ExpertRuleLine { get; set; }

    /// <summary>
    /// Gets or sets additional data in JSON format.
    /// </summary>
    [Jsonb]
    public string? MoreData { get; set; }

    /// <summary>
    /// Gets or sets foreign key linking the alerttype table to the ast table.
    /// </summary>
    public int? AlertTypeId { get; set; }
}
