<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.17" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.9.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.8.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\arc.app\arc.app.csproj" />
    <ProjectReference Include="..\arc.common\arc.common.csproj" />
    <ProjectReference Include="..\arc.data\arc.data.csproj" />
    <ProjectReference Include="..\arc.identity\arc.identity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
