<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="arc.api.testing" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.6" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\arc.common\arc.common.csproj" />
    <ProjectReference Include="..\arc.data.model\arc.data.model.csproj" />
    <ProjectReference Include="..\arc.domain\arc.domain.csproj" />
    <ProjectReference Include="..\arc.identity\arc.identity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Config\Forms\ExpertRules\" />
    <Folder Include="Config\Reports\Footers\" />
  </ItemGroup>

</Project>
